### PR TITLE
change node verson to >= 6.0.0

### LINKED ISSUE #32: Node 7
```bash
master* $ yarn add --dev gulp-svg2png                                                                                        
yarn add v0.17.3
[1/4] Resolving packages...
warning gulp-svg2png > svg2png > phantomjs-prebuilt > request > node-uuid@1.4.7: use uuid module instead
[2/4] Fetching packages...
error gulp-svg2png@2.0.2: The engine "node" is incompatible with this module. Expected version "^6.0.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

master* $ node -v
v7.1.0
```

I think it's better to use something like `>=6.0.0` in `engines` field.

### PR DESCRIPTION
**Pull request by farwayer**
fix #32

### CODE REVIEW

**Comment by sunnykgupta** [comment]
+1

**Comment by miketaylorco** [comment]
+1

**Comment by shakyShane** [comment]
Any chance this be published to NPM as it's breaking our builds :)

Thanks

**Comment by allenfantasy** [comment]
+1 for the current version in NPM (2.0.2) is breaking our builds in node>=7

**Pull request merged**
