### PR TITLE
Feature/parallel tasks

### PR DESCRIPTION
**Pull request by nihaopaul**
resolves  Max user processes #7 
* added in one extra module for backwards compatibility
* added in a flag to limit parallel tasks
* updated documentation

Todo
* create a test case

### CODE REVIEW

**Comment by mediafreakch** [comment]
+1 !

**Comment by artem-malko** [comment]
+1 !

**Comment by thild42** [comment]
+1 !
Please, merge this PR. This is a must have feature.

**Comment by akoenig** [comment]
@nihaopaul Awesome. Thanks for contributing. Live in `1.0.0`. Woop, woop! :)

**Comment by tledouarin** [comment]
Thanks for merging this PR. That's really great.

**Comment by sillero** [comment]
Awesome work!!!

Thanks :D

**Pull request merged**
